### ISSUE TITLE
401 Forbidden

### ISSUE THREAD

**Issue by bengineer19** [highlycaffeinated/mailgun-js#268]
Might be wrong but it seems that there might be a problem with authorisation?

Using the most basic sample:
```
var API_KEY = "foo";
var DOMAIN = "bar";
var mailgun = require("mailgun-js")({ apiKey: API_KEY, domain: DOMAIN });

const data = {
  from: "Excited User <mailgun@MYDOMAIN>",
  to: "MY_PERSONAL_EMAIL",
  subject: "Hello",
  text: "Testing some Mailgun awesomeness!",
};

mailgun.messages().send(data, (error, body) => {
  console.log(body);
  console.log(error);
});

```

I get a 401 forbidden:
```
Error: Forbidden
    at IncomingMessage.<anonymous> (C:\Users\benja\meet-new-people\node_modules\mailgun-js\lib\request.js:327:17)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  statusCode: 401
}
```

When everything is working fine with curl using the same API key. j/domain etc.

See other recent questions on stackoverflow reporting same issue:

https://stackoverflow.com/questions/63489555/mailgun-401-forbindden

and https://stackoverflow.com/questions/63601030/how-to-send-emails-with-mailgun-in-nodejs

**Comment by bengineer19** [comment]
My bad - it came down to setting the `host` as 'api.eu.mailgun.net' for EU zones.

**Comment by felixmariotto** [comment]
I had the same problem than @bengineer19, but I will elaborate a bit on his last comment above : 

The issue was that I added a new domain which I thought was located in EU because my app server is located in EU. But apparently what Mailgun wants to know is where is the DNS located, not your app server. In my case since it's NameCheap, it was in the US, not the EU...

I deleted the recorded EU domain on the Mailgun website, and recrated it but indicated in the US.

**Comment by j2is** [comment]
This is a highly undocumented and confusing issue. In the example node config why not put an example for this? Anyway the answer just for clarity is that for node it should be specified like this:

```
var mailgun = require("mailgun-js")({
  apiKey: 'XXXXX',
  host: "api.eu.mailgun.net",
  domain: "mailgun.examplewebsite.com",
});
```
